language: node_js
node_js:
- '6.9.0'
services:
- mysql
- redis
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
notifications:
  slack:
    secure: SlpY9HUA8yJveU7VJTAcJpCMSxMD9+4MvEktFvv4RdwhfGQMmmWdHUk6kIa/l52TvFRRzUMGaD93N00E0b3eTs1OhTEhubLQ62NBLc5r6UdQ7WO0oVsO6bQJIOFgV7imEdxu5wtLyn7+lFCCA+n6fExnHDy04V1D+psvHEZvoAg=
